#!/usr/bin/perl
# This is an EXTREMELY cheap hack to get gtest XML output working under
# the hudson CI server.  To use it, simply call:
# gtest-hudson.pl <input XML file generated by gtest> <output dir to write to>
# This script is intended as a workaround until gtest has the ability to
# write single XML files per class, as JUnit does.

$INFILE = $ARGV[0];
$OUTDIR = $ARGV[1];
print "ARGS -> $INFILE, $OUTDIR\n";

$state = 0;
open(BLAH, "<", $INFILE) or die "Cannot open '$INFILE': $!";

while($line = <BLAH>) {
  if($line =~ /.*<testsuite.*/) {
    if($state == 0) {
    }
    elsif($state == 1) {
      if($line =~ /.*name="(?:\S+\/)?(\S+)".*/) {
        $filename = $OUTDIR . "/" . $1 . ".xml";
        open(FILE, ">", $filename) or die "OMG, cannot open '$filename': $!";
        print FILE $line;
      }
    }
    $state++;
  }
  elsif($line =~ /.*<\/testsuite>.*/) {
    $state--;
    print FILE $line;
    close(FILE);
  }
  elsif($state > 1) {
    print FILE $line;
  }
}

close(BLAH);
